name: flutter_flow_chart
description: draw a flow chart diagram with different kind of customizable elements. Dashboards can be saved for later use.
version: 3.0.0
homepage: https://github.com/alnitak/flutter_flow_chart

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  convert: ^3.1.1
  cryptography: ^2.7.0
  encrypt: ^5.0.3
  feedback: ^3.1.0
  flutter:
    sdk: flutter

  # https://pub.dev/packages/uuid
  flutter_colorpicker: ^1.1.0
  flutter_echarts: ^2.5.0
  http: ^1.2.1
  mqtt_client: ^10.2.1
  path_provider: ^2.1.3
  shared_preferences: ^2.5.3
  star_menu: ^4.0.1
  syncfusion_flutter_charts: ^29.1.33
  syncfusion_flutter_gauges: ^29.1.33
  typed_data: ^1.3.2
  uuid: ^4.4.0
  web_socket_channel: ^3.0.1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets\images\branding\CSIR_logo_1.png

